version: '3'
services:
  db:
    image: postgres
  redis:
    image: redis
  proxy:
    restart: always
    build:
      context: ./proxy
    ports:
      - '80:80'
  sinatra:
    build:
      context: ./sinatra
    environment:
      - PGHOST=db
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgrespassword
      - PORT=8080
      - APP_ENV=production
      - COUNTERHOST=counter
      - COUNTERPORT=8080
  counter:
    build:
      context: ./counter
    environment:
      - PORT=8080
      - APP_ENV=production
      - REDISHOST=redis
