version: '3'
services:
  sinatra:
    build:
      context: ./sinatra
    ports:
      - "8080:8080"
    environment:
      - PGHOST=192.168.100.166
      - PGDATABASE=oag
      - PGUSER=jakub
      - PGPASSWORD=password
      - PORT=8080
      - APP_ENV=production
      - COUNTERHOST=counter
      - COUNTERPORT=8081
  counter:
    build:
      context: ./counter
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - APP_ENV=production
