version: '3'
services:
  proxy:
    restart: always
    build:
      context: ./proxy
    ports:
      - '80:80'
  sinatra:
    build:
      context: ./sinatra
    environment:
      - PGHOST=192.168.100.166
      - PGDATABASE=postgres
      - PGUSER=jakub
      - PGPASSWORD=password
      - PORT=8080
      - APP_ENV=production
      - COUNTERHOST=counter
      - COUNTERPORT=8080
  counter:
    build:
      context: ./counter
    environment:
      - PORT=8080
      - APP_ENV=production
