apiVersion: apps/v1
kind: Deployment
metadata:
  name: sinatra-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: web
  template:
    metadata:
      labels:
        component: web
    spec:
      containers:
        - name: sinatra
          image: jakubmi/el-sinatra
          ports:
            - containerPort: 4567
